name: "Feature request"
description: Request a new feature
labels: ["type: feature"]
body:
  - type: markdown
    attributes:
      value: |
        This project's goal is to remain aligned with [sonner](https://sonner.emilkowal.ski). If the feature you are requesting is not in the original sonner, it will not be considered here.
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the feature
      description: A clear and concise description of the feature. If you intend to submit a PR for this feature, tell us how in the description. Thanks!
      placeholder: Feature description
    validations:
      required: true
